# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'register-deployments-elasticsearch-action'
description: 'This action allows to index deployments and their statuses in a specified ES instance'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'book-open'
  color: 'green'
inputs:
  application-id:
    description: 'The application id to register the deployment for'
    required: true
  version:
    description: 'The version of this deployment'
    required: true
  index:
    description: 'In which index should the deployments be tracked'
    required: false
  environment:
    description: 'The environment in which the application is running'
    required: false
    default: "local"
  service-id:
    description: 'The service id to register the deployment for'
    required: false
    default: "null"
  meta:
    description: 'A JSON object containing any meta information required'
    required: false
    default: "{}"
  status:
    description: 'Indicating if this deployment has failed or succeeded'
    required: false
    default: "false"
outputs:
  doc-id:
    description: 'The document ID'
  doc:
    description: 'The JSON of the registered doc'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - send
    - "{\"application_id\":\"${{ inputs.application-id }}\",\"version\":\"${{ inputs.application-id }}\",\"environment\":\"${{ inputs.environment }}\",\"status\":${{ inputs.status }},\"meta\":${{ inputs.meta }},\"service\":\"${{ inputs.service-id }}\"}"
    - ${{ inputs.application-id }}-${{ inputs.version }}-${{ inputs.environment }}-${{ inputs.service-id }}
    - ${{ inputs.index }}
